name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community

      - name: Commit metrics
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push
