name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories
          config_timezone: America/Bogota

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_lines: yes

           # Isometric calendar
      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: isometric-calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: America/Bogota

              # Recent activity
      - name: Generate recent activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: recent-activity.svg
          base: activity
          config_timezone: America/Bogota

      # About me with enhancements
      - name: Generate about me
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: about-me.svg
          base: ""
          plugin_about: yes
          plugin_about_title: yes
          plugin_about_resume: "Hi, I'm Cristian. I love building tools that automate and visualize data. Curious by nature."
          config_timezone: America/Bogota



      # Programming languages
      - name: Generate coding languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          config_timezone: America/Bogota

      - name: Commit metrics
        
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add github-metrics.svg
          git commit -m "chore: update metrics" || echo "No changes"
          git push

